### PR TITLE
added vim-surround as a default plugin

### PR DESCRIPTION
**Pull request by muream**
First pull request ever here, I'm not too comfortable with git either so I just learned about submodules, which are pretty cool!
If i'm doing anything wrong, please tell me!

### CODE REVIEW

**Comment by badosu** [comment]
To be frank, I think it would be better to have _less_ bundled plugins instead of more, but I understand why one would want to have that plugin.

**Comment by muream** [comment]
I did it since I saw [this issue](https://github.com/onivim/oni/issues/1998) I should probably have stated this in the PR.
I do agree that to many plugins is a bad idea but one of Oni's goals is to lower the bar for new users. Anyone coming from VSCode, Atom, etc. will expect a way to surround text with quotes, parenthesis, etc.

**Comment by bryphe** [comment]
Looks great, @muream ! Thanks for taking this on!

@badosu - I like the feedback you left on #1998 - being more explicit about the set of plugins we bring in as part of the default configuration (as opposed to the opaque `oni.useDefaultPlugins` setting we have today...). My plan is to start looking at this as part of a more complete plugin management story for the next release.

So I think it's reasonable to bring this in now, to be bundled with our existing set of 'default' plugins - and then orthogonally we'll work on a better story for being explicit and managing that default set as we delve into plugin management.

**Comment by bryphe** [comment]
Will bring this in now. Thanks again @muream ! 👍 Congrats on the first PR! This might finally give me a reason to learn vim-surround 😄 

In parallel, we'll continue investigating ways to improve our default-plugin story as part of a holistic plugin management scenario.

**Comment by muream** [comment]
Thanks @bryphe ! Hopefully you can expect more and more PRs from me!

**Pull request merged**
