### PR TITLE
Bugfix/path concatenation

### PR DESCRIPTION
**Pull request by Akin909**
@bryphe, whilst investigating a solution to #1061, I realised that swapping out `shell-env` for the call to `childProcess.exec` does not actually work the same way i.e. logging the path output of both processes, `shell-env` correctly picks up the path and plain process call doesn't once the app is built. I hadn't realised that that wasn't working as I still had the additional env variables set in my config so it was picking up my executables which led me to believe the process exec method was working.

With `shell-env` things appear to work correctly and the `which go-langserver` returns the correct response. Apologies thought we had cracked it earlier and wouldn't need the extra dependency, which I've re-added. I've also left out shell-env's associated dependencies and just installed shell-env.

### CODE REVIEW

**Comment by Akin909** [comment]
As a side note, which has led to a bit of confusion on my end,  the `PATH` variable echo'ed by `term` in nvim does not seem to reflect the path that the neovim process is using, which is very confusing but in effect if you run `echo $PATH` (no `!`) as an `excommand` you see a path which is what I think neovim uses however the path for the terminal *in nvim in oni* seems to have ?extra or different access as the variable it outputs does not match that.

The `term` path variable in my case seems to include extra separators as I noticed in #1061 but the nvim `echo $PATH` output does not 😕

**Comment by Akin909** [comment]
Apologies for what is beginning to feel like a stream of consciousness/rant, whilst adding shell env seemed to return the correct path, unfortunately in `go` files it was not picking up hover info for external libs etc. I think this is due to the fact that `go` depends on things like `GOROOT` and `GOPATH` environment variables. I've resolved this by merging the default process.env from `electron` with `shell-env`'s environment which gives the user access to all their shell variables.

This solves the problem of finding dependencies based on shell vars and also allows user to have access to all their shell variables, which at least for me is quite helpful as my vimrc references shell variables I or other programs set up.

screen shot 2017-12-03 at 20 28 00

**Comment by josemarluedke** [comment]
Thanks for working on this @Akin909.

I can confirm that this solves the problem reported in #1061.

**Comment by bryphe** [comment]
Thanks for catching this and fixing it, @Akin909 ! Sorry I led you down the wrong path in terms of `childProcess.exec` versus `shell-env`. 

> I think this is due to the fact that go depends on things like GOROOT and GOPATH environment variables. I've hopefully resolved this by merging the default process.env from electron with shell-env's environment.

Awesome! Yes, this makes sense.

Thanks @josemarluedke for confirming the fix, too! I suspect this could impact #868 as well, as the python provider is sensitive to not having the appropriate paths to load the python runtime.

**Comment by bryphe** [comment]
Oh and this is interesting:

> The term path variable in my case seems to include extra separators as I noticed in #1061 but the nvim echo $PATH output does not 😕

I wonder if this is specific to Oni, or if it happens in `nvim` too?

Change looks good to me - the test failures on TravisCI don't seem related to your change (and when I ran locally, they passed). I'll take a look at those failures.  Thanks again for the investigation + fix here, @Akin909 !

**Comment by Akin909** [comment]
@bryphe through very superficial perusing of issues re neovim's terminal I *think* it sources it's `path` differently as it's essentially another program embedded in nvim. Re the fix I tried it locally yesterday with no issues except I can't get `reason` running yet but that pre-dates this issue (I haven't set it up properly yet I think) but I made some tweaks since then and think my local build (which includes my experiments is no longer properly sourcing the tss) will the tests pick that up? if not i'd like to revert some changes rebuild and make sure there aren't any issues there.

**Comment by bryphe** [comment]
@Akin909 - in theory the tests should pick it up (which may be why it is failing in the CI machine) - at least the AutoCompletion-TypeScript test should fail if we're unable to start `tss` (it looks like that is the test that is failing). The Demo-Screenshot test is also dependent on it, since it waits for the completion UX to show to generate the screenshot.

> if not i'd like to revert my build back to this commit and make sure there aren't any issues there.

If you wouldn't mind double-checking, that'd be great! I'll double-check on my machine too. I'll hold off on bringing it in until we confirm that `tsserver` is starting correctly.

**Comment by Akin909** [comment]
@bryphe sorry false alarm re `tss` I've got it running, I was experiencing some crashes in the console due to some plugin tinkering, but I've built a version off of that branch i've got a functioning `tss`

screen shot 2017-12-04 at 17 23 49

**Comment by bryphe** [comment]
@Akin909 Oh ok, great, thanks for the update! I built locally and it is working for me as well.

I'll bring this in, and investigate the stability of those tests.

**Pull request merged**
