### PR TITLE
[ISSUE-246]: Add --help option to command-line oni

### PR DESCRIPTION
**Pull request by someguynamedmatt**
> based on #246 

- Added `--help` (also `-h`) to command line initialization
sample output:

args

### CODE REVIEW

**Comment by bryphe** [comment]
Thanks for taking this on @someguynamedmatt !

One thing I realized is that unfortunately this won't address #246 completely - the `cli/oni` script is _only_ used for running via `npm` (`npm link`) - I don't believe it's used when Oni comes from any of the packaged binaries unfortunately.

**Comment by someguynamedmatt** [comment]
Ah, okay. I'll keep poking around then.

**Comment by someguynamedmatt** [comment]
@bryphe Is there a trick to getting a packaged build locally? I have another solution, but I'd like to test it out before harassing you with PRs 😄

**Comment by someguynamedmatt** [comment]
@bryphe Okay, this should be better. I've tested it on OSX by packaging the app, installing it locally, and handing it `--help`. Seems functional. I can't get the packaging to work on Linux, though I'd assume it would work as well. Let me know what you think. And, as always, suggestions welcome!

**Comment by bryphe** [comment]
Looks good to me! I just tried it on Windows, and there is a bit of weirdness happening with `stdin`/`stdout` here, but I think this is a pre-existing issue:
image

(Somehow, the output gets printed _after_ the prompt - it's strange!)

**Comment by bryphe** [comment]
But it makes sense to bring this in - we can tackle the windows issue separately. Thanks for the contribution, @someguynamedmatt ! 👍

**Pull request merged**
