### PR TITLE
Feature/add keyboard binding to browser

### PR DESCRIPTION
**Pull request by Akin909**
Add `h,j,k,l` binding to the browser layer to scroll left, down, up, right. Relates #1952 

TODO:

- [x] Find a better gate to check if browser is active - any ideas @bryphe  as this needs to be in the `Keybindings.ts` but you have a variable in `Browser/index.tsx` which is a record of active layers by id.

### CODE REVIEW

**Comment by CrossR** [comment]
>Find a better gate to check if browser is active - any ideas @bryphe as this needs to be in the Keybindings.ts but you have a variable in Browser/index.tsx which is a record of active layers by id.

Not any help, but just agreeing it would be nice. 
If the UI elements surfaced a "isSelected" bool via the API that would be great. I've found myself wanting that for both the browser and the Explorer/Sidebar, either for Tests or keybinds.

**Comment by Akin909** [comment]
@CrossR that would be nice to have a general mechanism to query to know what the selected part of the editor was at any given time 👍, there is a mechanism for the sidebar though or rather in #1839, I found the pieces to put one together though a more general API method would be nice.

@bryphe just read the comments you left in #1952 more thoroughly and it answers the above question 😆

**Comment by Akin909** [comment]
@bryphe regarding the search functionality I plan to leave that out for the time being since I think that will actually probably be a bit more involved than the commands I've added so far so I plan on making a separate pr for that

**Comment by bryphe** [comment]
This is super cool @Akin909 ! Just tried it out, I really like it... can't wait to use it in my workflow 👍 

> @bryphe regarding the search functionality I plan to leave that out for the time being since I think that will actually probably be a bit more involved than the commands I've added so far so I plan on making a separate pr for that

Sounds good to me!

> Not any help, but just agreeing it would be nice.
If the UI elements surfaced a "isSelected" bool via the API that would be great. I've found myself wanting that for both the browser and the Explorer/Sidebar, either for Tests or keybinds.

Ya, it would be nice to have this - I guess we just need to figure out what form the API should take?

**Pull request merged**
