### PR TITLE
#943 - Split bundle via async imports

### PR DESCRIPTION
**Pull request by bryphe**
This is the first part of an improvement in startup time. Today, we need the browser to load the entire large `bundle.js` before it can start rendering.

This change leverages the async `import` functionality, along with webpack's ability to chunk along the async boundaries, such that we can kick start some operations and parallelize the loading.

This is a first step, but helps to improve loading.

### CODE REVIEW

**Comment by bryphe** [comment]
There may be some duplication across bundles - should look at incorporating the CommonChunksPlugin as well.

**Comment by Akin909** [comment]
@bryphe may or may not be relevant to what your trying to do here or potentially a rabbit hole, though seemed worth mentioning a new `js` bundler called [`Parcel`](https://github.com/parcel-bundler/parcel) it simplifies a lot of what webpack does through painful configuration and endless plugins, it supports `TS` and `Less`

**Comment by bryphe** [comment]
Ah ya, interesting! It does look easy and straightforward.

I'm wondering too if we can just avoid making bundles altogether - just point Electron to the output `index.js`. This would save us a lot of compile time, and might actually be more efficient in terms of loading. The version of Node that Electron has today unfortunately doesn't support the `import` method, but once Electron 2 is out, it might be worth profiling w/o any bundler.

**Comment by bruchmann** [comment]
There’s also [electron-link](https://www.npmjs.com/package/electron-link) that might help with [improving startup time](http://blog.atom.io/2017/04/18/improving-startup-time.html).

> electron-link is a node module that takes a JavaScript file (typically the entry point of an application) and a list of modules that need to be required lazily (see Atom's build scripts for an example). Then, starting from that file, it traverses the entire require graph and replaces all the forbidden require calls in each file with a function that will be called at runtime. The output is a single script containing the code for all the modules reachable from the entry point. This file can be then supplied to mksnapshot to generate a snapshot blob.

**Comment by bryphe** [comment]
Thanks for the pointer, @bruchmann ! We're tracking leveraging v8 snapshots in #381 , just added some context there - `electron-link` looks like it would be very helpful for that.

**Pull request merged**
