### PR TITLE
Switch to 'tabs.mode': 'tabs' by default

### PR DESCRIPTION
**Pull request by bryphe**
This changes the default value of `'tabs.mode'`: `'tabs'`. This is (hopefully) the culmination of several discussions around whether to default to `buffers` vs `tabs`:
- #1174
- #1563 
- #1627 

The main concern I had was in creating an experience that is familiar to users coming from Atom / VSCode - where there is a 1:1 tabs to buffers, so I defaulted that setting to buffers. What I've found though is that this leads to very confusing behavior for existing Vim users, and also that it may not be mutually exclusive. I believe that we can satisfy the 'users coming from Atom/VSCode/Sublime' case in 'tabs' mode, with minor tweaks, by just keeping 1 tab === 1 buffer by default from the QuickOpen/Explorer. 

The main changes are:
- Switch to tabs.mode setting of 'tabs' by default (and potentially deprecate the 'buffers' setting, if possible)
- Set up the QuickOpen selection behavior to open in a _new tab_ if the file is not already open, or an _existing tab_ if it is already open. Same for file explorer. This is different than the current default, which was using `:e` - opening the buffer in the existing tab. I'm interested if this will impact / break anyones workflow. `Control+T` in the QuickOpen selection behaves as it does today, always opening a new tab. 

In addition, @CrossR  has unblocked this by giving our 'tabs' mode parity in functionality with 'buffers' mode in #1498 - thanks @CrossR ! 💯

Given all the feedback around the 'buffers' default, I think pivoting and trying out the 'tabs' default makes sense for the next release - cc  @jordwalke  @badosu@hoschi, as I know you all were impacted by this. The goal here is to have a system that is intuitive for both vim users and new users, without sacrificing power or flexibility 👍

### CODE REVIEW

**Comment by badosu** [comment]
I like this change, I think that if we have an editor capable of potentiating the VIM experience and deliver it with quality we'll be able to safely be able to experiment new ideas.

**Comment by Akin909** [comment]
@bryphe when you say potentially deprecate the `buffers` setting does this mean by default all users will have to work with `tabs`, definitely not wanting to restart what have been many discussions, but it seems like anyone with a primarily buffer based workflow coming from vim would only be able to use tabs? 😞

Might just wait to see what the change ends up looking like since I interact very little/never with tabs 😟

**Comment by bryphe** [comment]
> when you say potentially deprecate the buffers setting does this mean by default all users will have to work with tabs

Only if people aren't using it! I wish I had telemetry - it's hard to gauge how many users had explicitly set 'tabs' vs 'buffers'. But I won't deprecate it if its useful. 

> Might just wait to see what the change ends up looking like since I interact very little/never with tabs 😟

Ya, it'll be interesting to see if it works for you, or if you have to flip back to 'buffers' mode. I heard the confusion / issues around the 'buffers' default in those linked issues - I'm curious what the response will be when it is flipped to 'tabs'.

**Comment by badosu** [comment]
I know that the buffer list navigation mode is popular among vim users as well, so I think it's good to not remove that.

**Comment by bryphe** [comment]
Cool, I'll include this as a 'breaking change' in the release notes for next release - we'll give it a shot and see how it works 👍

**Pull request merged**
