### PR TITLE
Bump to Neovim 0.3.0

### PR DESCRIPTION
**Pull request by CrossR**
Depends on my open PR in the `oni-neovim-binaries` being merged first.

### CODE REVIEW

**Comment by badosu** [comment]
Do you know what this package does for each OS? Just wondering how this could impact Linux Distros.

**Comment by CrossR** [comment]
Yep, the code is pretty simple:

https://github.com/onivim/oni-neovim-binaries/blob/master/lib/postinstall.js

```
    await releaseDownloader.downloadGithubRelease(path.join(__dirname, ".."),  {
        "user": "neovim",
        "repo": "neovim",
        "tag": "v0.3.0",
        "platforms": {
            "win32": {
                "name": "nvim-win32.zip"
            },
            "win64": {
                "name": "nvim-win64.zip"
            },
            "darwin": {
                "name": "nvim-macos.tar.gz"
            }
        }
    })
```

So this will not change Linux behaviour at all. If a Linux user wants Nvim 0.3.0 they'd simply have to update their nvim binary on their machine in whatever way they normally do (download an appimage, `apt`/`pacman` etcetc)

Since we only bundle Neovim for Window and Mac, we don't need to make any changes to the Linux side of things, except for maybe Arch AUR build scripts and similar, though they aren't kept in the repo.

**Comment by badosu** [comment]
@CrossR Thanks for the detailed explanation.

Do we have a place where we state the minimum neovim version Oni supports? If this change gets merged, does that change to 0.3.0?

**Comment by CrossR** [comment]
The Wiki has some stuff here, and perhaps in other places : https://github.com/onivim/oni/wiki/Installation-Guide#linux

That said, we aren't using any features of 0.3.0 yet, so its not going to break anything. However, once #2302 is added, we will need to bump the required version number.

**Comment by badosu** [comment]
@CrossR Great, thanks! I'll keep that in mind when #2302 is merged and a new version is released!

**Comment by bryphe** [comment]
Awesome, thanks @CrossR ! I just published the new version of `oni-neovim-binaries@0.1.2`, and verified it picks up the latest `nvim`. I'll restart the builds here.

**Comment by bryphe** [comment]
Woohoo! Build is good now - thanks @CrossR for getting us upgraded to the latest Neovim! I'll bring this in now in preparation of our next release 👍

**Pull request merged**
