### PR TITLE
Added .nvmrc with node@9

### PR DESCRIPTION
**Pull request by someguynamedmatt**
- [Install nvm](https://github.com/creationix/nvm#installation)
- `nvm use` from command line

I can add these steps in the development documentation.

### CODE REVIEW

**Comment by bryphe** [comment]
Sweet, thanks for adding this @someguynamedmatt !

**Comment by bryphe** [comment]
Just curious - do you have the option to squash and merge now? If so - go for it! 👍

**Comment by someguynamedmatt** [comment]
@bryphe I would, but I don't have merge options available to me.

**Comment by bryphe** [comment]
Ah ok, thanks for letting me know. Wasn't sure if the button would be enabled w/ an approval. Bringing it in now 👍

**Pull request merged**
