### PR TITLE
Various cleanup within tutorials

### PR DESCRIPTION
**Pull request by keforbes**
I've been trying to keep a holistic view of the tutorials and cleaning them up when needed.  This Pull Request is another batch of fixes to cleanup wording, add some re-enforcement of learning, and general consistency.

- Notes:  the `d` and `c` Notes had "`Examples:`" at the end of their description because in the `d` and `c` tutorials they were followed by more example keys.  However, this made it awkward to use `d` and `c` as reminders in other tutorials.  I removed the "`Examples:`" from the description for ease of re-use.

- Delete Operator: Now that the `t`/`T`/`f`/`F` tutorial takes place before the `d`elete operator I decided to add examples of `dtx` to show how delete can be combined with those motions.

- Inline Finding: Cleaned up the wording and gave more explicit directions of how the feature is expected to be used.  I also added more steps for re-enforcement.

- Undo: added Redo to the tutorial so the user can learn both at the same time.  Now a user will know what to do if they accidentally hit undo.

- Search: Originally, the Search tutorial taught `?` for reverse search but then immediately had steps for `N` to do a backwards-reverse search, which I felt was confusing.  Instead, I now start at the bottom of the file and search backwards with `n` before reversing to show how `N` differs.

- Target.vim:  I had filed #2243 because the only `Stage` used in this tutorial was the `MoveToGoalStage` so the entire tutorial could be completed with only movements.  I fixed this so it actually checks for line changes.  Also, there were a lot of steps which would use `c` as the operator but would then tell the user to hit `esc` without making a change.  I feel like that's a bad habit to develop so I changed them to either insert some text as part of the change or changed it to a `d`elete operation instead.

- Motion tutorials:  Most of the motion tutorials had titles like "Motion: _, 0, $" or "Motion: w, e, b" which I don't think was descriptive enough.  So I gave them all more descriptive titles like "Search Motion" and "Word Motion".  The default width of the sidebar might be too cramped for the titles I gave but the word-wrap works fine so I think this is acceptable.

### CODE REVIEW

**Comment by keforbes** [comment]
I'm hoping to get this Pull Request in before the next release.  I have a coworker who has been talking about learning Vim so I plan on forcing him to go through these tutorials and give me feedback. :laughing:

**Comment by bryphe** [comment]
Thanks @keforbes ! Really appreciate you taking a holistic view of the tutorials 👍 

Just played through the latest ones in the change - I like the added repetition. It's starting to feel like a pretty substantial amount of content to play through it all (which is great). I also realize I forget to use some motions, like `t` - great to be reminded.

I'll bump the release and bring this change in - would be great to have some fresh feedback on our tutorials!

**Comment by bryphe** [comment]
Got this in for 0.3.6!

BTW @keforbes - do you have an e-mail I can reach you at? My email is bryphe@outlook.com

**Comment by keforbes** [comment]
I told my coworker to download Oni and give me feedback on the tutorials.  He made it halfway through before he had to email the rest of the team about it, who then immediately forwarded the email to a wider audience.  So no real feedback other than total praise and compliments. :smile:

**Comment by bryphe** [comment]
@keforbes - that's awesome! 😄

**Pull request merged**
