### PR TITLE
Feature/add new file in explorer

### PR DESCRIPTION
**Pull request by Akin909**
This PR adds the ability to create a new file or folder in the explorer, these are bound to `<c-e>` and `<c-f>` by default both actions are also undoable by pressing `u`, duplicates result in an error notification. Relates #1839 based off of #2115 (should be merged after 2115)

new

### Todo:
- [x] Add Tests

### CODE REVIEW

**Comment by tarciozemel** [comment]
@Kxze #2129

**Comment by Kxze** [comment]
This is awesome! Thanks for implementing my request :)

**Comment by bryphe** [comment]
Very cool, @Akin909 ! Can't wait to start using this in my workflow! You've done an amazing job making the explorer useful 💯 

I noticed one minor quirk that was a bit confusing for me at first:
add file

When I'm highlighted on an item, and I press `<C-e>` or `<C-f>`, it shows the insertion UX _before_ the item - that made me think it might put the file in the wrong place. In the example above, I pressed `<c-f>` on `test-rename2`.  

I would've expected the insertion UX is shown _after_ the item - that way, it feels like it will be inserted into `test-rename2`.

It might be even more apparent on the root (which is super cool that it works and I can insert a file/folder there!): 
image

But I would expect that it would show the 'insert' UX _after_ the root, instead of before.

**Comment by Akin909** [comment]
@bryphe I've tweaked the insertion UX to show after the selected item (it was a completely arbitrary decision on my part in the first place and easily fixed 😄)

**Comment by bryphe** [comment]
Sweet, looks great @Akin909 ! 😀 Glad it was a straightforward change, the behavior is much more intuitive to me 👍

**Comment by bryphe** [comment]
@Jimeno0 , you're in luck! These actually made it into our 0.3.4 release: https://github.com/onivim/oni/releases/tag/v0.3.4 😉 Would ❤️ feedback.

Of course, you can always build from the latest `master` to pick up the newest stuff - instructions here: https://github.com/onivim/oni/wiki/Development

We also have the latest `master` binaries available for download (for backers) here: https://www.onivim.io/Insiders

**Comment by Jimeno0** [comment]
Wohaaaa I thought that I was using the 0.3.4 but it turns I wasnt! 😃

(If you go to the [installation guide](https://github.com/onivim/oni/wiki/Installation-Guide#mac) and then search for the download Oni for mac it downloads the 0.3.2)

Im currently using Oni at work so I will try the latest master version and give you all my feedback :)

About the explorer commands I can just say... this is f**ing amazing!😍

Some little thing that disrupts me are that if you delete a file the cursor goes to the top of the explorer and when I try to delete several files I ended deleting files that I didnt want to (its just a mather of time to get use to it but I found it interensting to let you know)

Also whit the new feaure I no longer can use <C-d> to go down for a few lines  (as I use to do in vim), it deletes the cursor file.

Those are just minor stuff, I hope that feedback helps. And again these new features are insane guys! Thanks for such an amazing editor 😍

**Pull request merged**
