### PR TITLE
[WIP] Fix east asian width issue

### PR DESCRIPTION
**Pull request by ackey**
Some characters (ex. ①: aka "Ambiguous" width characters) are cut in half.

ambiguous

This PR adds "editor.useEastAsianWidth" option. (The default value leaves false)
Enabling this option fixes the issue. (You also need "set ambiwidth=double" in init.vim)

### CODE REVIEW

**Comment by justinmk** [comment]
> This PR adds "editor.useEastAsianWidth" option

What's the purpose of that, instead of just letting `ambiwidth` control the decision?

**Comment by ackey** [comment]
Even with `ambiwidth=double`, those ambiguous characters are cut in half.

Oni uses `wcwidth()` under the hood to get the character width. It returns `1` for those ambiguous characters.
This option uses `eaw.getWidth()` (https://github.com/mysticatea/eaw) instead of that. It returns `2` for those ones.

**Comment by justinmk** [comment]
My question is why add another setting? In other words, let the fixes you made be controlled by `ambiwidth` instead of a new Oni setting?

I'm not quiet sure about Oni's position regarding new settings. Is it typical to add Oni settings even if a Nvim setting already exists?

**Comment by ackey** [comment]
Oh, now I understand the meaning of your question.
Yes, the idea to use existing Nvim's setting seems to be good 🙂 
I don't know the method now, but I will try to find it.

**Comment by Akin909** [comment]
@ackey I think there are few issues that currently surround rendering of ambiwidth characters including #2427 so definitely appreciate the PR.

Re. re-implementing `nvim` features @justinmk cant speak for everyone but I think we've avoided re-implementing anything nvim already provides and stuck to just nice to have gui things, or non-native features and is something I personally think is v. important since that will just bloat and overcomplicate oni needlessly.

@ackey do you know whether setting ambiwidth resolves the issue? (or improves it the canvas renderer is know to clip text due to a very involved issue I cant find), note though re this PR and that solution anyway that the canvas renderer is a strategy we are trying to eventually move away from in favour of the `webgl` renderer so this will only solve the problem there.

**Comment by ackey** [comment]
@Akin909 setting ambiwidth doesn't resolve the issue.

The cursor is next to the character in the bellow.

Oni: ambiwidth=double
oni-double

Oni: ambiwidth=single
oni-single

Nvim: ambiwidth=double
nvim-double

Nvim: ambiwidth=single
nvim-single

These are all ok except that the character is clipped in Oni.

This is not the canvas rendering issue. The character isn't actually clipped but the program code fills the right-hand side of the character with the background color rectangle.

**Comment by Akin909** [comment]
@ackey thanks for looking into it and the images, I wonder if the results are the same if you set `editor.renderer: "webgl"`, re. solution that wouldn't involve oni taking control of this setting, we can read via the nvim api the value of a setting such as `ambiwidth`

> nvim_get_option({name})                                    *nvim_get_option()*
>                Gets an option value string
>
>                Parameters: 
>                    {name}  Option name
>
>                Return: 
>                    Option value (global)

from the docs,

we could then use that as the boolean to check, currently at work but can flesh out when I'm free when and how you could get access to the variable in both of the renderers

**Comment by justinmk** [comment]
See also the `option_set` redraw event in `:help ui-global`. Since Nvim 0.3.0, 'ambiwidth' and other UI-related options are published in the `option_set` event.

**Comment by ackey** [comment]
@Akin909 @justinmk Thank you for the information 🙂 

@Akin909 webgl looks perfect without this solution 😍 

webgl: ambiwidth=double
webgl-double

webgl: ambiwidth=single
webgl-single

**Comment by Akin909** [comment]
@ackey since the issue seems to relate to the canvas renderer vs. the webgl one its known issues is it alright to close this PR with the definitive fix being eventually fully migrating to the webgl renderer

**Comment by ackey** [comment]
I'm using the webgl renderer now and it seems it's perfect to me. I close this PR. Thanks 🙂

**Pull request closed without merging**
