### PR TITLE
[WIP] Added coloring option for dirty-marker

### PR DESCRIPTION
**Pull request by wheyerstrass**
As dicussed with @Akin909 and @hoschi in #1580 I created a styled component that replaces the current dirty-marker. Its `background-color` can be customized using the configuration key `editor.dirtyMarker.userColor`, which accepts css color values and defaults to the current themes `foreground` color.

### CODE REVIEW

**Comment by Akin909** [comment]
@wheyerstrass great work on the PR just a couple of notes re. the config option I think we have a couple related to the tab so the marker option would be best grouped with those e.g. `tab.dirtyMarker.color` re. the failing tests we have some test in place for the tabs under `ui-tests/Tabs.test.tsx` I think the snapshot will need updating using `yarn test:unit:react -u`

**Comment by wheyerstrass** [comment]
Looking through the travis-ci log it looks like the job has been terminated because this happens in a loop:  
```
[20094:0704/160417.525607:INFO:CONSOLE(1)] "[REDUX - LANGUAGE][ACTION] CURSOR_MOVED", source: file:///home/travis/build/onivim/oni/dist/linux-unpacked/resources/app/lib/browser/bundle.js (1)
[20094:0704/160417.526410:INFO:CONSOLE(1)] "[REDUX - NeovimEditor0][ACTION] SET_WINDOW_CURSOR", source: file:///home/travis/build/onivim/oni/dist/linux-unpacked/resources/app/lib/browser/bundle.js (1)
[20094:0704/160417.527114:INFO:CONSOLE(1)] "[SyntaxHighlighting.notifyViewportChanged] - bufferId: 1 topLineInView: 484 bottomLineInView: 514", source: file:///home/travis/build/onivim/oni/dist/linux-unpacked/resources/app/lib/browser/bundle.js (1)
```
Is this a test I can reproduce locally ? `yarn run test` and `yarn test:react` pass.  
Could this be related to my prior merge with onivim/master ?

**Comment by Akin909** [comment]
@wheyerstrass I've re-run the CI test and they pass (they flake out on occasion, which is known were trying to resolve that) thanks for the PR looks good and for making the changes 👍

**Comment by Akin909** [comment]
Just realised you still had a WIP flag on this lemme know if I jumped the gun and we can revert it and re-open the PR sorry about that should have checked in first

**Comment by wheyerstrass** [comment]
@Akin909 I wanted to make the config to dirty-marker component passing more robust, because right now this line:  
```js
background-color: ${props => props.userColor || props.theme.foreground}
```
would fail if `userColor === ""`
I'd add that and then remove the WIP.

**Comment by wheyerstrass** [comment]
@Akin909 Ok it looks like it does work as expected. I don't know why  
`"" | "a"` evals to `0` but  
`a | "a"` evals to `"a"` if `a === ""`

**Pull request merged**
