### PR TITLE
[ISSUE #1300]: <space> rather than literal

### PR DESCRIPTION
**Pull request by someguynamedmatt**
#1300 @bryphe I think this is the solution to the issue, assuming I understood the issue _correctly_ 😄

### CODE REVIEW

**Comment by bryphe** [comment]
Changes look great to me, @someguynamedmatt ! Looks like the right spot to me 😄 

Could you please add a test to cover this case as well? We have some cases for this started here:
https://github.com/onivim/oni/blob/9ba6f55b6ee5664e9b7cea8651e2e2368fca3309/browser/test/Input/Keyboard/ResolverTests.ts#L19

It should be pretty similiar to the existing case we have there, except for space instead of backspace.

You can test it by running `npm run test:unit:browser`, or debug it via `npm run debug:test:unit:browser`.

Thanks for the PR, appreciate it!

**Comment by someguynamedmatt** [comment]
@bryphe I’m always forgetting the tests. Lol. I’ll get that up soon.

**Comment by someguynamedmatt** [comment]
@bryphe Good to go.

**Comment by bryphe** [comment]
Excellent, looks great! 👍

**Comment by bryphe** [comment]
Linux failure isn't related to your change, so I'll bring this in now. Thanks for the contribution, @someguynamedmatt ! 👍

**Pull request merged**
