### PR TITLE
Enable use of middle click to close tabs

### PR DESCRIPTION
**Pull request by texhnolyze**
Enables closing oni tabs with middle click, much like e.g. firefox/chrome.
Corresponds to #2069. 

**Do not merge yet:**
As mentioned in the issue there is still some clarification needed
concerning the ability to close tabs, when only a single one is opened and how to go 
about testing clicks/middle clicks of tabs to ensure they are correctly selected and closed.

### CODE REVIEW

**Comment by keforbes** [comment]
> Do not merge yet:

Please put `[WIP]` at the beginning of the Pull Request's title (Work In Progress) until the Pull Request is ready.

**Comment by keforbes** [comment]
Feel free to edit the title and remove `[WIP]` when you're ready to go. :slightly_smiling_face:

**Comment by bryphe** [comment]
Thank you for the PR, @texhnolyze ! The functionality change looks great to me 👍 

Would it be possible to add a test case to exercise this behavior? I'm wondering if we could use the [simulate](http://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html) method to exercise the normal click and non-middle button click, and check if the correct `onTabClosed` and `onTabSelect` callbacks from the props are executed as expected?

**Comment by texhnolyze** [comment]
@keforbes thanks, will do in the future
@bryphe ok once I am finished with this I will open a new issue concerning the single tab behaviour.
Concerning the test I will have another try to get that working, however due to the the async nature of `FileIcon` (as described in the issue) the way I see it the only two ways to get that test working is injecting `FileIcon` as a dependency so that I can mock it out in the test easily (which would require quite a bit of change), overwriting the actual imported `FileIcon` in tabs or actually setup the underlying async `IconThemes` first and turn the test more into an integration test. Not sure what the best option would be.

**Comment by texhnolyze** [comment]
@bryphe yeah took my some trial and error, but this is finished from my side for this pull request, if you already had a look at the changes you probably saw what I did with the `classnames` dependency ([commit](https://github.com/onivim/oni/pull/2190/commits/cf6df8d3821a09420b0450bcf3933e5c49b0bc02)).

This works for now, but I would suggest maybe dropping the dependency in favor of an own implementation, because as it currently stands it does not seem like there will be a [new release soon](https://github.com/JedWatson/classnames/issues/152). The implementation of this as a project component should be failrly trivial. What do you think?

Also now that I know a bit more about the test setup and jest and so on, I'll do a pull request, when I find the time, to add a bit more test coverage and to get to know the code base better.

**Comment by bryphe** [comment]
Merged - thank you for the contribution, @texhnolyze ! 💯

**Pull request merged**
