### PR TITLE
[blocker] Switch to styled-components

### PR DESCRIPTION
**Pull request by samvv**
So there are starting to get a lot of open pull requests, but if possible, I'd like to get this one merged first when ready. Some tests are failing currently because they do not play nice with the `less` imports. This pull request should not change anything for the end-user, only for the developer by using [styled-components](https://www.styled-components.com/), thereby addressing issue #1132.

There are a few minor side-effects, which I think are beneficial:
 
 - [x] Components have now direct access to `state.colors` through `props.theme` thanks to `ThemeProvider`
 - [x] Error markers now become active on the correct line when setting the cursor to that line

### CODE REVIEW

**Comment by bryphe** [comment]
> So there are starting to get a lot of open pull requests, but if possible, I'd like to get this one merged first when ready.

Cool, I'll hold off on any CSS change PRs while you're working on the conversion to minimize merge issues.

**Comment by samvv** [comment]
Thanks, I'm trying to finish it as soon as possible, as I understand this can be inconvenient.

**Comment by samvv** [comment]
I'm going to have to call it a day, unfortunately. Will continue working on it tomorrow 🔥 Cheers!

**Comment by bryphe** [comment]
> I'm going to have to call it a day, unfortunately. Will continue working on it tomorrow 🔥 Cheers!

Sounds great! Thanks for all your work so far, @samvv  - looks like excellent progress! I really like this approach. 👍 

@Akin909 - I see what you meant about how nice it is to be able to pass the `props` in - that's really cool.

**Comment by samvv** [comment]
No problem, I really want to see this project succeed 😄 It will probably take a couple of days before I'm completely done, and it will have to be thoroughly reviewed. Other than that, I don't encounter any major problem.

**Comment by Akin909** [comment]
@bryphe It's an amazing library which I think will fit really well with `Oni` as there so many situation where having styles react directly to props is *sooo* helpful plus I think incorporating the `ThemeProvider` is another big boon going forward

**Comment by samvv** [comment]
@Akin909 Agreed, the `ThemeProvider` will make it so much easier for the user to define his or her own styles. 🎉

**Comment by bryphe** [comment]
Cool, just read a bit about `ThemeProvider` in the docs - it seems much cleaner than what we have today in terms of passing around the colors explicitly in the props. I like the idea of having the root `<ThemeProvider />` and having `props.theme` available... looking forward to that.

**Comment by samvv** [comment]
@bryphe Unfortunately some other projects require all of my attention at the moment. I'd suggest merging it as it is now. I've only pushed changes of code that has been tested and should work, and that way someone else can finish the job. Perhaps @Akin909? And no worries, I'll be back 😄

**Comment by bryphe** [comment]
> @bryphe Unfortunately some other projects require all of my attention at the moment. 

No worries, thanks for the heads up!

> I'd suggest merging it as it is now. I've only pushed changes of code that has been tested and should work, and that way someone else can finish the job. Perhaps @Akin909?

Sure thing! It looks like there are a few build issues (perhaps lint errors) - I'll take a look and finalize those. I'll merge this in, and then address those/get builds green in a separate PR. 

I'm happy to work on converting some of the remaining `less` files to `styled-components` as it will give me a chance to learn more about it. Let me know @Akin909 if that's something you're interested in too - don't want us to duplicate work 😄 

> And no worries, I'll be back 😄

Awesome 👍 Really appreciate your contributions to the project so far!

**Comment by Akin909** [comment]
@samvv @bryphe happy to help, ps you did an amazing job in a very short space of time @samvv 👍 , re help I've commented over in #1114 (the gist is happy to do some if you point me towards what to start with)

**Pull request merged**
