### PR TITLE
[WIP] File Explorer v2

### PR DESCRIPTION
**Pull request by bryphe**

### CODE REVIEW

**Comment by badosu** [comment]
Really can't tell too much without testing this, but I was wondering whether we could reuse something for the logic and just stylize the output? If this requires more boilerplate than what we are saving then great (or has fundamental limitations/flaws), if not I would suggest:

- (NerdTree) https://github.com/scrooloose/nerdtree
- (vim-vinegar) https://github.com/tpope/vim-vinegar
- vim's native netrw

**Comment by bryphe** [comment]
Some progress:
image

Still a lot left, though!

**Comment by bryphe** [comment]
> Really can't tell too much without testing this, but I was wondering whether we could reuse something for the logic and just stylize the output?

Thanks for looking at it, @badosu ! I wanted to test a few things as part of this change - one of them brought up in #622 - the idea of having Oni control the render layer, but using Neovim as the input layer (which I believe would work well for any non-modifiable list-type UI, like the quickfix in #730). This allows us to keep things like smooth-scrolling, while getting the benefit of respecting the user's keybindings and customizations.

It'll be a bit more work but I think it'll be worth it in the long run, as it will push us further from terminal limitations and enable us to do some more interesting things in the UX layer. Thinking of features like a version control pane, or a debug pane - it'd be nice to interact with those in a vim-consistent way, while having a UX that is on-par with Atom/VSCode. That's my dream for Oni, anyway 😉

**Comment by bryphe** [comment]
This is almost live (well, behind a feature flag) in #1104 - will track remaining work there.

**Pull request closed without merging**
