### PR TITLE
Use yarn to run npm sripts (#2057)

### PR DESCRIPTION
**Pull request by texhnolyze**
because for dev setup previously yarn was used to install
dependencies while npm was used to run build and setup a
symlink to use local oni from shell resulting in issues

### CODE REVIEW

**Comment by texhnolyze** [comment]
Are people actively using the ```install-global``` and ```uninstall-global``` npm scripts? If not I would like to remove them as yarn actively deprecates the ```yarn install -g```  and ```yarn remove -g``` methods as it is not recommended to install packages globally. What do you guys think?

**Comment by Akin909** [comment]
@texhnolyze I have never actually run either command and I'm not actually sure where they are being used @bryphe might know if they are needed, I think personally that if they are being deprecated and they aren't actively being used then removing them sounds fine 👍 

PS: thanks for the PR looks good

**Comment by bryphe** [comment]
Excellent, thanks for getting us all-in on `yarn`, @texhnolyze ! Looks good to me too.

> Are people actively using the install-global and uninstall-global npm scripts? If not I would like to remove them as yarn actively deprecates the yarn install -g and yarn remove -g methods as it is not recommended to install packages globally. What do you guys think?

Nope, these are _very_ old scripts that aren't being used anymore - would be great to remove them. Appreciate you taking a pass through these!

**Comment by texhnolyze** [comment]
@Akin909 I tested the npm scripts to make sure there is no unexpected behaviour after the switch to yarn and have not encountered any issues. 
To the second question, ```yarn install``` installs a packages (either by name or ```package.json```), while ```yarn add``` is used to add new depencies to the ```package.json``` and generate a new lock file. It used to be the case that the two would have the same effect when adding dependencies, which is not the case anymore as add replaced install for that.

@bryphe removed those two npm scripts, so this is merge ready from my side. Also will update the wiki/docs once it is merged.

**Pull request merged**
