### PR TITLE
Feature/Add AppImage and archlinux support

### PR DESCRIPTION
**Pull request by barni2000**
I have configured the electron-builder for AppImage and archlinux.

### CODE REVIEW

**Comment by Akin909** [comment]
Does anyone who uses linux want to give this a try @CrossR? it looks good to me but I won't be able to test this unfortunately

**Comment by barni2000** [comment]
zenity, kdialog, Xdialog is dependency for a message "Would you like integrate ... ". It assumes that you have a fully installed X environment. With this application can appear in your menu. It registers the desktop file.

**Comment by barni2000** [comment]
electron-builder create this script https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/linux/AppRun.sh for run.

**Comment by badosu** [comment]
@barni2000 What's the output for the pacman target? Seems like a good way to automate the package generation.

**Pull request closed without merging**
