### PR TITLE
Add Tutorial: Copy & Paste

### PR DESCRIPTION
**Pull request by keforbes**
This creates a Copy & Paste tutorial, dependent on a new `WaitForRegisterState.tsx` class I created which validates the correct contents are found in the unnamed register.  I've overloaded the constructor so named registers can use this class in later, more advanced, tutorials.

As part of this Pull Request, I also reordered some of the other tutorials.  I moved the SearchInBufferTutorial to be the last "motion" tutorial which is then followed by the "delete" tutorials.  I think this flows better since it means the "delete" tutorials flow into the "copy & paste" tutorial which utilizes delete (and the concept of "nouns" and "verbs").

Also, one minor issue.  On my system, when copying, if I hit `y` and then wait for the editor to show `OPERATOR` mode, and then hit `w`, the `WaitForRegisterState` check works perfectly.  But if I hit `yw` quickly, it just sits there and waits for me to hit any other key before it recognizes the register was updated.  I did this development within a VM so maybe I'm introducing unnecessary lag/delay but I wanted to mention it in case others can reproduce it.  Although if you *can* reproduce it, I don't think the fix would be in my code.

### CODE REVIEW

**Comment by keforbes** [comment]
Fixes #2035.

**Comment by bryphe** [comment]
> This creates a Copy & Paste tutorial, 

Just tested it out - very nice 😄 

> dependent on a new WaitForRegisterState.tsx class I created which validates the correct contents are found in the unnamed register. I've overloaded the constructor so named registers can use this class in later, more advanced, tutorials.

Awesome, that's great! Perfect if we add a tutorial for using the registers (or even perhaps macros, or the visual mode registers...). Thanks for making it reusable.

> As part of this Pull Request, I also reordered some of the other tutorials. I moved the SearchInBufferTutorial to be the last "motion" tutorial which is then followed by the "delete" tutorials. I think this flows better since it means the "delete" tutorials flow into the "copy & paste" tutorial which utilizes delete (and the concept of "nouns" and "verbs").

Makes sense! I imagine organizing them will be sort of incremental as we add more and identify natural groupings.

> Also, one minor issue. On my system, when copying, if I hit y and then wait for the editor to show OPERATOR mode, and then hit w, the WaitForRegisterState check works perfectly. But if I hit yw quickly, it just sits there and waits for me to hit any other key before it recognizes the register was updated. 

I actually noticed this too - for me, if I yank, it doesn't register as a success until I move the cursor.

I believe the issue is with the code here: 
https://github.com/onivim/oni/blob/d51ca84b9916120679a45ff8808070a0d0ddc563/browser/src/Services/Learning/Tutorial/TutorialGameplayManager.ts#L67

Right now, we only `tick` on a very limited set of events - mode changed, cursor moved, and buffer changed. In the case of yanking, it doesn't fall into that narrow set of categories, and therefore we never tick - so the `WaitForRegisterState` never gets a chance to say its complete. If I move the cursor, it forces a tick, and then we hit the completion criteria.

I think that as the tutorials get more involved, we'll need a 'real' game loop, like:
```
window.setInterval(() => {
   this._tick()
}, 250)
```

(The alternative would be that we could keep hooking events... but that might get tricky!)

The only challenge there is we want to make sure to clear that interval when the tutorial is over or the buffer is closed. We could track this in a separate issue, as you mentioned, it's not your tutorial code at fault.

**Comment by bryphe** [comment]
BTW, we tweaked our 'contributing' guidelines a bit - as a collaborator, feel free to merge in your own PRs.

They just require approval from one other collaborator - and you also have the ability to approve PRs. I approved this one so you're good to go. 👍 

Let me know if you have any questions!

**Comment by keforbes** [comment]
> BTW, we tweaked our 'contributing' guidelines a bit - as a collaborator, feel free to merge in your own PRs.

I still prefer to keep you in the loop so I'm not sneaking anything in without your knowledge. :smile:

**Comment by keforbes** [comment]
I'll pull this in since the fix for #2050 will resolve any lingering issues here.  As long as #2050 is fixed before the next release, no users will notice this oddity of the yank tutorial.

**Comment by bryphe** [comment]
> I still prefer to keep you in the loop so I'm not sneaking anything in without your knowledge. 😄

Haha, you actually don't have to worry about that - github will actually enforce that one other collabarator  'approves' it - and if both a submitter and collaborator are cool with the change, I'm cool with it too 👍 But of course I'm happy to be looped in if there are any questions or concerns.

#2049 is a good example of a PR going in without waiting on me. It's awesome to have the help reviewing PRs - means I'm not a bottleneck 😄

**Pull request merged**
